### ISSUE TITLE
Error on startup with current eXist develop

### ISSUE THREAD

**Issue by joewiz** [wolfgangmm/exist-markdown#2]
After starting up current eXist develop, loading the markdown app at http://localhost:8080/exist/apps/markdown/ redirects to http://localhost:8080/exist/apps/markdown/test.md, which yields the following error:

```
<exception>
    <path>/db/apps/markdown/parse.xql</path>
    <message>
        err:XQST0033 error found while loading module md: Error while loading module content/markdown.xql: Cannot bind prefix 'md' to 'http://exist-db.org/xquery/markdown' it is already bound to 'http://exist-db.org/metadata'
    </message>
</exception>
```

The key bit:

> Cannot bind prefix 'md' to 'http://exist-db.org/xquery/markdown' it is already bound to 'http://exist-db.org/metadata'

The registration of this prefix appears to stretch back to 2012 - according to https://github.com/eXist-db/exist/commit/c33a2fadb29bd90a1b3c1a1b8dd29ab4533bafef - so it's very odd that we haven't seen this before!

**Comment by joewiz** [comment]
@wolfgangmm I'm happy to submit a PR changing the module namespace prefix `content/markdown.xql` from `md` to something different like `markdown`, and the other modules that reference this module in this app and in fundocs. But before I do this I wanted to make sure that this is the approach you'd like? The only other one I can think of is to un-register @shabanovd's metadata module, which would require that it be manually imported in the same way the console module is. That would suggest that the metadata extension be moved to a standalone .xar. But all this has implications beyond the present app - so I wanted to check with you on the desired approach.

**Comment by wolfgangmm** [comment]
@joewiz ok, changing the prefix for the markdown app is probably the easiest approach.

**Comment by joewiz** [comment]
I did a directory diff of the 0.4 release from public-repo against the clone of the github repo. The only thing in the 0.4 release that wasn't in the github repo was the release notes for 0.4.  I added these back in to source control, and prepared the new version for release as 0.5.
